import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'core/router/app_router.dart';
import 'core/theme/app_theme.dart';
import 'services/notification_service.dart';

// TODO: Replace dart-define values with actual project credentials before building
const _supabaseUrl = String.fromEnvironment(
  'SUPABASE_URL',
  defaultValue: 'https://your-project.supabase.co',
);
const _supabaseAnonKey = String.fromEnvironment(
  'SUPABASE_ANON_KEY',
  defaultValue: 'your-anon-key',
);

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialise Supabase
  await Supabase.initialize(
    url: _supabaseUrl,
    anonKey: _supabaseAnonKey,
    debug: kDebugMode,
  );

  // Initialise Firebase (skip on web if not configured)
  try {
    await Firebase.initializeApp();
    // Initialise FCM after Firebase is ready
    if (!kIsWeb) {
      await NotificationService.instance.initialize();
    }
  } catch (e) {
    // TODO: Add firebase_options.dart generated by FlutterFire CLI before first build
    // Run: flutterfire configure --project=your-firebase-project
    debugPrint('Firebase init skipped (not configured): $e');
  }

  runApp(
    const ProviderScope(
      child: DhammaSchoolApp(),
    ),
  );
}

class DhammaSchoolApp extends ConsumerWidget {
  const DhammaSchoolApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(appRouterProvider);

    return MaterialApp.router(
      title: 'Dhamma School',
      theme: AppTheme.light(),
      routerConfig: router,
      debugShowCheckedModeBanner: false,
      localizationsDelegates: const [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        // TODO: Add AppLocalizations.delegate once gen-l10n is configured
        // AppLocalizations.delegate,
      ],
      supportedLocales: const [
        Locale('en'),
        Locale('si'), // Sinhala
      ],
    );
  }
}
